// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package partialanalysis

// GeneratedPayload simulates auto-generated schema struct
type GeneratedPayload struct {
	ID        string `json:"id"`
	Payload   []byte `json:"payload"`
	Timestamp int64  `json:"timestamp"`
}
